// Generated by gencpp from file robot_1/OddEvenCheck.msg
// DO NOT EDIT!


#ifndef ROBOT_1_MESSAGE_ODDEVENCHECK_H
#define ROBOT_1_MESSAGE_ODDEVENCHECK_H

#include <ros/service_traits.h>


#include <robot_1/OddEvenCheckRequest.h>
#include <robot_1/OddEvenCheckResponse.h>


namespace robot_1
{

struct OddEvenCheck
{

typedef OddEvenCheckRequest Request;
typedef OddEvenCheckResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct OddEvenCheck
} // namespace robot_1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_1::OddEvenCheck > {
  static const char* value()
  {
    return "4ff0b0ab1ed04611e3a2b4090af9ee4f";
  }

  static const char* value(const ::robot_1::OddEvenCheck&) { return value(); }
};

template<>
struct DataType< ::robot_1::OddEvenCheck > {
  static const char* value()
  {
    return "robot_1/OddEvenCheck";
  }

  static const char* value(const ::robot_1::OddEvenCheck&) { return value(); }
};


// service_traits::MD5Sum< ::robot_1::OddEvenCheckRequest> should match
// service_traits::MD5Sum< ::robot_1::OddEvenCheck >
template<>
struct MD5Sum< ::robot_1::OddEvenCheckRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_1::OddEvenCheck >::value();
  }
  static const char* value(const ::robot_1::OddEvenCheckRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_1::OddEvenCheckRequest> should match
// service_traits::DataType< ::robot_1::OddEvenCheck >
template<>
struct DataType< ::robot_1::OddEvenCheckRequest>
{
  static const char* value()
  {
    return DataType< ::robot_1::OddEvenCheck >::value();
  }
  static const char* value(const ::robot_1::OddEvenCheckRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_1::OddEvenCheckResponse> should match
// service_traits::MD5Sum< ::robot_1::OddEvenCheck >
template<>
struct MD5Sum< ::robot_1::OddEvenCheckResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_1::OddEvenCheck >::value();
  }
  static const char* value(const ::robot_1::OddEvenCheckResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_1::OddEvenCheckResponse> should match
// service_traits::DataType< ::robot_1::OddEvenCheck >
template<>
struct DataType< ::robot_1::OddEvenCheckResponse>
{
  static const char* value()
  {
    return DataType< ::robot_1::OddEvenCheck >::value();
  }
  static const char* value(const ::robot_1::OddEvenCheckResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_1_MESSAGE_ODDEVENCHECK_H
