(cl:defpackage robot_1-srv
  (:use )
  (:export
   "CAMERA"
   "<CAMERA-REQUEST>"
   "CAMERA-REQUEST"
   "<CAMERA-RESPONSE>"
   "CAMERA-RESPONSE"
   "ODDEVENCHECK"
   "<ODDEVENCHECK-REQUEST>"
   "ODDEVENCHECK-REQUEST"
   "<ODDEVENCHECK-RESPONSE>"
   "ODDEVENCHECK-RESPONSE"
  ))

